version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - user=${HOST_USER:-laravel}
        - uid=${HOST_UID:-1000}
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/supervisor/conf.d:/etc/supervisor/conf.d
    ports:
      - "8000:8000"
    networks:
      - laravel-network
    depends_on:
      - db
      - redis
    command: ["supervisord", "-c", "/etc/supervisor/supervisord.conf"]
    environment:
      - SUPERVISOR_PIDFILE=/var/www/storage/logs/supervisord.pid
      - HOST_UID=${HOST_UID}
      - HOST_USER=${HOST_USER}
  
  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_USER: laravel
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - laravel-network

  redis:
    image: redis:alpine
    container_name: laravel_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - laravel-network

volumes:
  dbdata:
    driver: local
  redis_data:
    driver: local

networks:
  laravel-network:
    driver: bridge