[program:temperature-importer]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/artisan app:import-temperature /var/www/example.csv
autostart=true
autorestart=false
startretries=5
startsecs=60
numprocs=1
stdout_logfile=/var/www/storage/logs/importer.log
stdout_logfile_maxbytes=0
stderr_logfile=/var/www/storage/logs/importer-error.log
stderr_logfile_maxbytes=0